# ============LICENSE_START=======================================================
# dcaegen2-collectors-veshv
# ================================================================================
# Copyright (C) 2019 NOKIA
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-counting-consumer-deployment
  namespace: onap
  labels:
    app: hv-collector-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hv-collector-kafka-consumer
  template:
    metadata:
      labels:
        app: hv-collector-kafka-consumer
        name: kafka-counting-consumer
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/monitoring/prometheus"
    spec:
      containers:
        - name: kafka-consumer-counting
          image: onap-dev-local.esisoj70.emea.nsn-net.net/kjaniak/consumer:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: LISTEN_PORT
              value: "8080"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: performance-test-config
                  key: consumer.kafka.bootstrapServers
            - name: KAFKA_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: performance-test-config
                  key: consumer.kafka.topics
            - name: DISABLE_PROCESSING

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-processing-consumer-deployment
  namespace: onap
  labels:
    app: hv-collector-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hv-collector-kafka-consumer
  template:
    metadata:
      labels:
        app: hv-collector-kafka-consumer
        name: kafka-processing-consumer
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/monitoring/prometheus"
    spec:
      containers:
        - name: kafka-processing-consumer
          image: onap-dev-local.esisoj70.emea.nsn-net.net/kjaniak/consumer:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: LISTEN_PORT
              value: "8080"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: performance-test-config
                  key: consumer.kafka.bootstrapServers
            - name: KAFKA_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: performance-test-config
                  key: consumer.kafka.topics

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-counting-consumer
  namespace: onap
  labels:
    app: hv-collector-kafka-consumer
spec:
  selector:
    name: kafka-counting-consumer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6062
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-processing-consumer
  namespace: onap
  labels:
    app: hv-collector-kafka-consumer
spec:
  selector:
    name: kafka-processing-consumer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6063
      targetPort: 8080
