global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-processing-consumer'
    metrics_path: '/monitoring/prometheus'
    static_configs:
      - targets: ['kafka-processing-consumer:6064']

  - job_name: 'kafka-offset-consumer'
    metrics_path: '/monitoring/prometheus'
    static_configs:
      - targets: ['kafka-offset-consumer:6062']

  - job_name: 'ves-hv-collector'
    metrics_path: '/monitoring/prometheus'
    static_configs:
      - targets: ['ves-hv-collector:6060']
